const express = require('express')
const app = express()
const swaggerUi = require('swagger-ui-express')
const swaggerFile = require('./swagger._output.json')
const env = require("dotenv")
env.config({path:"./config/.env"})
const cors =require("cors")
const db = require("./config/db")
const superadmin = require("./routes/admin_routes")
const superadminLogin =require("./routes/adminLogin_-routes")
const customer = require("./routes/customer_routes")
const officeAdmin = require("./routes/office_routes")
const forgotPasswordforAdmin =require("./routes/forgotPasswordforsuperAdmin")
const docket =require("./routes/docket_routes")
const billing = require("./routes/billing_routes")
const enquiry =require("./routes/enquiry_routes")
const DeliveryBoyDetails =require("./routes/DeliveryBoyDetails_routes")
const PickupDetails =require("./routes/pickupDetails_routes")
const MenifestDetails =require("./routes/menifestDetails_routes")
const InscanDetails =require("./routes/Inscan_routes")
const PODDetails =require("./routes/PodDetails_routes")
const DRSDetails =require("./routes/DRSDetails_routes")
const GroupDetails =require("./routes/GroupDetails_routes")
const state = require("./routes/state_routes")
const city = require("./routes/city_routes")
const status =require("./routes/status_routes")
const Address =require("./routes/Address_routes")
const package =require("./routes/package_routes")
const contents =require("./routes/contents_routes")
const mode =require("./routes/mode_routes")
const driver =require("./routes/driver_routes")
const vehical =require("./routes/vehical_routes")
const deliveryBoyLogin =require("./routes/DeliveryBoy_login_routes")
const docketDelivery =require("./routes/DocketDelivery_routes")
const menifestbyflight = require("./routes/menifestbyflight_routes")
const menifestbytrain = require("./routes/menifestbytrain_routes")
const menifestbyroad = require("./routes/menifestbyroad_routes")
const allocation = require("./routes/Allocation_routes")
const MenifestbyDocket = require("./routes/menifestbyDocketMapping_routes")
const DocketbyDRS = require("./routes/docketDrs_routes")
const Datarange= require("./routes/datarange_routes")
const billingItem= require("./routes/billingItem_routes")
const HSNCode= require("./routes/HSNCode_routes")
const podImage= require("./routes/podImage_routes")
const billingbyDocket= require("./routes/BillingbyDocketMapping_routes")
const Report = require("./routes/Reports_routes")
const contact = require("./routes/contactus_routes")

db()
app.use(express.json())
app.use(express.static('public'));
app.use(cors())
app.use('/api/v1',superadmin)
app.use('/api/v1',superadminLogin)
app.use('/api/v1/customer',customer)
app.use('/api/v1/officeAdmin',officeAdmin)
app.use('/api/v1/forgotPassword',forgotPasswordforAdmin)
app.use('/api/v1/docket',docket)
app.use('/api/v1/billing',billing)
app.use('/api/v1/enquiry',enquiry)
app.use('/api/v1',DeliveryBoyDetails)
app.use('/api/v1',PickupDetails)
app.use('/api/v1',MenifestDetails)
app.use('/api/v1',InscanDetails)
app.use('/api/v1',PODDetails)
app.use('/api/v1',GroupDetails)
app.use('/api/v1',state)
app.use('/api/v1',city)
app.use('/api/v1',status)
app.use('/api/v1',Address)
app.use('/api/v1',package)
app.use('/api/v1',contents)
app.use('/api/v1/DRS',DRSDetails)
app.use('/api/v1',mode)
app.use('/api/v1',driver)
app.use('/api/v1',vehical)
app.use('/api/v1',deliveryBoyLogin)
app.use('/api/v1',docketDelivery)
app.use('/api/v1',menifestbyflight)
app.use('/api/v1',menifestbytrain)
app.use('/api/v1',menifestbyroad)
app.use('/api/v1',allocation)
app.use('/api/v1',MenifestbyDocket)
app.use('/api/v1',DocketbyDRS)
app.use('/api/v1',Datarange)
app.use('/api/v1',billingItem)
app.use('/api/v1',HSNCode)
app.use('/api/v1',podImage)
app.use('/api/v1',billingbyDocket)
app.use('/api/v1',Report)
app.use('/api/v1',contact)

app.use('/swagger-api-doc', swaggerUi.serve, swaggerUi.setup(swaggerFile))
// swagger api http://192.168.43.220:37234/swagger-api-doc/
app.listen(process.env.PORT, () => console.log(`http://localhost:${process.env.PORT ||5000}`))
 // https://lalogistics.herokuapp.com/swagger-api-doc/
require('./endpoints')(app)
